src/settings.js
src/test_runner.js

This PR adds `--gather_trends`, without documentation

gather trends feature

---

package.json

See https://github.com/TestArmada/guacamole/pull/7

bump guacamole to 1.1.4 to support 'latest' version id

---

src/interop/magellan-nightwatch/get_tests.js
src/interop/magellan-nightwatch/rewrite_config.js

Supports nightwatch.conf.js, resolves #34

---

src/test_runner.js

I messed up this original pull request!  Some difference in my local testing branch and what I pull requested.  :frowning: sorry

Fixes reference to non-existing variable 'e'

---

src/sauce/settings.js
src/sauce/worker_allocator.js

Gracefully handle the outage of a locks server

---

package.json

Emergency fix: acorn updated a breaking change

Fix acorn crash due to acorn not using semver properly

---

bin/magellan

Fixes https://github.com/TestArmada/magellan/issues/84

check for existence of err object before calling stuff on it

---

.eslintrc
package.json
src/cli_help.js
src/sauce/tunnel.js
src/sauce/worker_allocator.js
src/test.js
src/test_filter.js
src/util/load_relative_module.js
src/worker_allocator.js

See: https://github.com/TestArmada/magellan/issues/69

[WIP] Add eslint, begin lint-cleaning process

---

src/test_runner.js

A logic error has prevented bail_fast and bail_early from working.

Fix bailout logic

---

package.json

Looks like #101 was merged to the "move-to-locators" branch after #100 was merged to master.

Fix for #101 merge

---

.travis.yml

Update travis config to test on:
* latest stable node
* iojs
* node 0.12
* node 0.10
/cc @Maciek416

add more node versions

---

src/test_runner.js
test_support/test_listener.js

Fix regression in listeners

---

package.json
src/reporters/admiral/reporter.js

Add debug information to help identify issues with Admiral

---

package.json
src/test_runner.js
src/util/process_cleanup.js
test/test_runner.js
test_support/fake_test.js

Allow child processes to gracefully exit but if they don't after a grace period, forcefully kill them.

Process Cleanup / Graceful Exit / Zombie Killer

---

package.json
src/sauce/browsers.js

this PR affects `--list_browsers`

Fix truncated browser

---

README.md
bin/magellan
package.json
src/global_analytics.js
src/mongo_emitter.js
src/test_runner.js
test/mongo_emitter.js

Mongo emitter

---

.travis.yml

apparently this is what's needed for codecov.io support?

codecov.io support

---

src/mongo_emitter.js

I guess I had it as `MAGELLAN_MONGO_DB` to start and then changed it to `MAGELLAN_MONGO_COLLECTION` and forgot to change it in both places. ;(

Fixing a dumb issue in the Mongo connector

---

.eslintrc
.travis.yml
bin/magellan
package.json
src/sauce/settings.js
src/sauce/tunnel.js
src/settings.js
src/util/port_util.js
test/cli.js

Linting to our ES5 standard, ahead of the change to ES6. ;)

Linting to our ES5 standard

---

package.json
src/profiles.js
src/test_runner.js
test/profiles.js

fix a bug where browser is undefined in console out

Fix profile output

---

bin/magellan
package.json
src/cli.js

this fixes the bug that `margs` is empty in `settings.js`

move marge to ./bin so it'll be initialized first

---

src/test_runner.js

Added check for empty listener

---

package-lock.json
package.json
src/util/childProcess.js

The new logging filter i put in place in previous release was filtering out the individual successful steps.
updated the stdout white list to include the check mark so those steps get picked up
Cheers!

fix bug with successful steps not showing in log

---

package.json
src/util/childProcess.js

The nightwatch logs were not showing correctly.
this PR fixes them to show correctly,
Code has been verified using a real world project with many test cases.
please see screenshot for verification of the code working correctly

fixed bugs with the nightwatch logs not showing up correctly

---

.travis.yml
package-lock.json
package.json

Addresses potential security vulnerabilities listed by dependabot by upgrading jest and yargs.

upgrade dependencies listed by dependabot

---

package-lock.json
package.json

Updates local executor to address dependency vulnerabilities.

updates local executor

---

package-lock.json
package.json

some teams/people still using node8, lets not break things for them :)

make-magellan-compatible-with-node8

---

package-lock.json
package.json
src/cli.js

update the yargs version and also print out the code version to console

Update the yargs version
