TestArmada/magellan

bin/magellan, magellan.json, package.json, src/detect-browsers.js, src/interop/lib/amend_node_config.js, src/interop/lib/get_mocha_tests.js, src/interop/lib/mocha_settings.js, src/interop/rowdy-mocha/get_tests.js, src/interop/rowdy-mocha/test_run.js, src/interop/vanilla-mocha/get_tests.js, src/interop/vanilla-mocha/test_run.js, src/settings.js, src/test_filter.js
This PR includes
- A shuffling of existing "vanilla" mocha support (for our existing convention-based appium support) to `mocha-vanilla`
- A new `mocha-rowdy` integration
- Fixes to by-test (`--test`) filtering for mocha-based test suites.
- node.js suite support (magellan can run its own tests using mocha-vanilla)
=> Initial mocha/rowdy support

README.md, src/cli_help.js, src/interop/rowdy-mocha/test_run.js, src/interop/vanilla-mocha/test_run.js, src/sauce/settings.js
PR notes:
- `--create_tunnels` is now required to use sauce connect. Magellan will otherwise skip tunnel creation. 
- The option previously known as `--no_tunnels` is now default
=> Tunnel Support for Mocha / Changes to Tunnel Defaults

README.md, src/sauce/settings.js, src/sauce/worker_allocator.js
- default at 1 tunnels instead of `max_workers`
- introduce `--max_tunnels` to allow an arbitrary number of tunnels to be used
/cc @geekdave
=> Tunnel sharing

bin/magellan, package.json, src/sauce/browsers.js
This PR adds an undocumented beta feature for adding unlisted devices. This is not intended to be `desiredCapabilities` "override" feature, and is subject to removal.
=> Add undocumented support for unlisted device addendums

README.md, package.json, src/cli_help.js, src/detect-browsers.js, src/hosted_profiles.js
Solves #30
This PR implements hosted profile support. Profiles can now be specified with an URL and a hash, like so:
```console
$ ./bin/magellan --profile=https://gist.githubusercontent.com/Maciek416/13c6e111d5814f22f1d6/raw/005387ad975b407bbed83a0dc44f1eab29e5ec29/profile.json#tier2
Loaded magellan configuration from: magellan.json
Sauce configuration OK
Loaded hosted profiles from https://gist.githubusercontent.com/Maciek416/13c6e111d5814f22f1d6/raw/005387ad975b407bbed83a0dc44f1eab29e5ec29/profile.json
Requested profile(s):  tier2
Running 28 tests with 7 workers with safari_7_OS_X_10_9_Desktop, IE_8_Windows_2008_Desktop, IE_9_Windows_2008_Desktop, IE_10_Windows_2008_Desktop
```
=> Hosted Profiles Support

src/test_filter.js
Improves error messages around parse errors (includes which file had a syntax
error)
=> Supports es6 tests, resolves #40

README.md
I noticed that using `--bail-time` didn't actually update the bail strictness in `test_runner.js` so it looks like snake-case options are required.
=> Updates docs to use snake-case for "bail_time"

src/main.js
A bad path has been inhibiting custom reporters from working. Also, `README` had an incorrect example for this feature (already updated in master).
=> Fix custom reporters -- bad path

README.md, src/sauce/settings.js, src/sauce/worker_allocator.js, src/test_runner.js, src/worker_allocator.js
This PR adds support for the upcoming `locks` server.
TODO:
=> Add support for a locks server for sauce VM allocation

bin/magellan
When using a test file with a `describe` block but no `it` statements the runner continues. This checks the length of the returned `tests` array in addition to its presence.
=> Bail when found tests array is empty

src/cli_help.js, src/settings.js
Sometimes, you want to use the same temp directory for multiple build processes in your project.
Usage: e.g.
`bin/magellan --temp_dir=build`
=> Add CLI option for temp directory

README.md, package.json, src/interop/lib/get_mocha_tests.js, src/interop/lib/mocha_tag_filter.js, src/interop/magellan-nightwatch/tag_filter.js, src/interop/rowdy-mocha/tag_filter.js, src/interop/vanilla-mocha/tag_filter.js, src/test_filter.js, test/test_runner.js
This PR adds the ability for magellan to filter tests by tag in mocha with `@tagname` support in `it()` strings.
/cc @geekdave
=> Support for tag filtering in mocha test suites

src/interop/lib/get_mocha_tests.js
This is the only instance of `acorn.parse` I could find that wasn't using `ecmaVersion: 6`. Had to add this to prevent this call from violently exploding in a project using ES6 with Mocha.
=> Parse mocha tests in es6 mode

src/reporters/slack/slack.js
`failure.browserErrors` may not always exist. Protect against accessing `.length`
=> Fix crash in Slack reporter when accessing browser errors list

src/interop/magellan-nightwatch/get_tests.js, test/nightwatch_test_iteration_and_filtering.js, test_support/mock_nightwatch_config.json, test_support/mock_nightwatch_tests/search.js, test_support/mock_nightwatch_tests/search_mobile.js, test_support/mock_nightwatch_tests/wiki.js
In the spirit of beefing up our test coverage and reducing irony factor (as mentioned by @mattfysh here https://github.com/TestArmada/magellan/pull/78 ), this PR preps for future tag filtering changes with some tests.
This PR adds:
- Some unit tests for `get_tests()` in nightwatch support
- Some more/better error handling in `get_tests()` (in nightwatch mode only) 
- Better visual output for what `get_tests()` is doing (in nightwatch mode only)
- A simple mock nightwatch test suite.
In the future, we want to be able to have `--tags` function in `OR` mode in addition the current `AND` mode, so adding tests before we add those functions is critical.
cc @geekdave
=> Add tests, more error handling, visual output for nightwatch get_tests functionality

.eslintrc, package.json, src/test_runner.js
This PR adds `eslint` to the build. Notes:
- There are many `eslint-disable` spots, but our intent should be to cover those spots with tests where necessary and work to reduce our lint-disables where sensible. `FIXME` notes have been added for the most egregious cases or where I want to make good but not in the scope of a housekeeping PR.
- Only `src/*` and `bin/*` are being scanned. Tests, test support, etc are TODO
/cc @geekdave
=> Add eslint to build for src/* and bin/*

README.md
Simply removes word "across" which used twice in the beginning of `README.md`.
=> Removes duplicate of word

src/test_runner.js
This PR fixes the incorrect saucelabs URL string in `test_runner`.
/cc @geekdave
=> Fix saucelabs URL

package.json, src/settings.js
Update `sauce-connect-launcher`, verbosely output where Magellan is outputting its temp files to the console.
/cc @geekdave
=> Log tempdir, update s-c-launcher

src/util/check_port_range.js, src/worker_allocator.js
Currently the only ports within the base port spacing range that magellan actually checks are `+ 0` and `+ 1`. 
This PR:
- updates magellan to check the entire range within the block given to the worker.
- cleans up the code a bit and puts port range checking into its own module.
- improves error messaging around occupied ports
/cc @geekdave
=> Check entire port range implied by spacing instead of just selenium and mock ports

src/util/process_cleanup.js
An improved zombie kill. We were assuming killing the immediate child pid would shut down the entire tree, but it doesn't seem to in all cases.
This time we use `kill()` which kills the entire tree of a child instead of `killPids` which only calls `killPid` for that one child internally.
=> Better zombie tree kill

src/sauce/worker_allocator.js, src/settings.js, src/test_runner.js, src/util/guid.js
This PR:
- Moves all cases where we do `Math.round(Math.random() * 99999).toString(16)` to `util/guid`.
- Introduces `acquire-worker-*****` to analytics output, for tracking how long it takes to acquire workers from the worker allocator (either directly or through an intermediary like https://github.com/TestArmada/locks )
=> Allocator analytics

bin/magellan, src/global_analytics.js, src/test_runner.js
This PR adds idle/busy tracking to `test_runner`, which in turn emits analytics events useful for tracking whether magellan is busy or idle, and for how long. Markers for `magellan-busy` are continuously marked **on the same event**, so this is thus far the only magellan analytics event that generates more than 2 markers in its lifecycle. This yields a marker pattern of:
`idle` -> `busy` -> `idle` -> `busy` -> [ ... ] - > `idle`
Examining the markers from a reporter can yield data which shows how much time magellan spent busy and how much time it spent idle.
/cc @geekdave
=> Track idle and busy states in analytics

src/sauce/browsers.js
This fixes the following error.
```
➜  magellan git:(master) bin/magellan --list_browsers
Magellan 8.4.0
Will try to load configuration from default of ./magellan.json
Loaded configuration from:  /Users/danielvicory/usr/src/magellan/magellan.json
Magellan is creating temporary files at: /Users/danielvicory/usr/src/magellan/temp
Sauce configuration OK
Couldn't fetch browsers. Error:  [TypeError: _.pluck is not a function]
TypeError: _.pluck is not a function
at Object.module.exports.listBrowsers (/Users/danielvicory/usr/src/magellan/src/sauce/browsers.js:27:31)
at /Users/danielvicory/usr/src/magellan/bin/magellan:126:14
at _fulfilled (/Users/danielvicory/usr/src/magellan/node_modules/guacamole/node_modules/q/q.js:834:54)
at self.promiseDispatch.done …
```
=> Use map with shorthand as pluck is removed in lodash 4

src/cli_help.js, src/settings.js, src/test_runner.js
This PR allows `--bail_early` to have its threshold and minimum test runs settings set.
Added:
- CLI help for both new options
- Clarification to log output of bail settings when early bail kicks in.
=> Make Early Bail Configurable via args/env, Clearer Bail Logging

package.json, src/settings.js, src/test_runner.js
Fixes #138 
Also checks if the resolved `TEMP_DIR` is writable, and calls `path.resolve` on `TEMP_DIR` before we add it to the global settings object.
/cc @geekdave
=> Sanitize string used for temporary asset directory path. Check TEMP_DIR exists and is r-w-able

README.md, src/main.js, src/util/check_ports.js, src/util/port_util.js, src/worker_allocator.js
This PR gives our users access to Magellan's port acquisition facilities, and allows users to **share Magellan's port cursor**. This ensures users are not stepping on top of Magellan's own guaranteed port range, and also ensures that if the user configures a specific port range, spacing, etc, everything agrees.
Documentation also updated
/cc @geekdave
=> Export port checking

src/settings.js
This fix for `settings.js` ensures that if someone were to pass in an `external_build_id` that yargs or marge provided as a _number_, we `toString()` and sanitize still works (which assumes a string).
/cc @archlichking @geekdave
=> Fix sanitize error when external build id is a number

src/test_runner.js, src/util/logstamp.js
Add time stamps to the output we gather from stdout/stderr of child processes.
=> Add time stamps to stdout/stderr stream output

src/test_runner.js
This PR blends all standard output from `stderr` and `stdout` of child processes into a single stdout. We color our prefixed timestamps red or green according to which stream the text came from so we can still see what was stderr and stdout. This fixes magellan's confusing out-of-order output for `stderr` and `stdout` when showing log output from failed tests.
/cc @archlichking
=> Blend both stdout streams but with different colors

README.md, bin/magellan, src/util/load_relative_module.js
This PR allows for some attached reporter modules to be marked as "optional".
This really means that if we fail to load an **optional** module due to `MODULE_NOT_FOUND`, the error will be ignored, and no unsettling warnings will appear.
/cc @archlichking @geekdave
=> Add optional reporters list to magellan.json

bin/magellan, src/sauce/worker_allocator.js, src/test_runner.js, src/util/process_cleanup.js
This PR fixes a bug where our zombie killing (`process_cleanup`) code sends `SIGKILL` to friendly sauce connect child processes which we later intend on closing gracefully. Since these sauce connect processes are never allowed to gracefully shut down, the tunnels remain open on Saucelabs, allowing tunnels to pile up. In cases where large numbers of builds happen frequently on a single account, this can easily break Saucelabs' per-account tunnel limit.
I've also quieted down our zombie killing code unless `--debug` is enabled. We still show zombie killing output if zombies are actually found.
Here's the bug in action:
In this state, when you sign onto saucelabs afterwards, you can see a lingering tunnel, which indicates the process was abruptly ended with `SIGKILL`. As a result, the tunnel …
=> Fix leaking of sauce connect tunnels and quiet down zombie killing output

README.md
- updates missing "test suites"
- adds the link for "See" in `bail_time`
=> few updates to README

README.md
These should probably be saved as dev deps as they aren't used in the production applications that use them at runtime. Thoughts? @geekdave @Maciek416 @archlichking @ThaiWood
=> Change npm install to save-dev in README

src/sauce/settings.js, src/sauce/tunnel.js
This PR adds support for the sauce connect launcher's "fast fail regexp" list, which allows for connections from sauce VMs to certain hostname patterns to be instantly failed.
/cc @geekdave @archlichking @ThaiWood
=> Add support for fast-failed connections in sauce tunnels

bin/magellan
This PR fixes an unhelpful error we get when selecting a profile name that doesn't exist:
```
01:53:24 Requested profile(s):  t2-safari8
01:53:24 Error initializing Magellan
01:53:24 
01:53:24 Error description:
01:53:24 TypeError: Cannot read property 'length' of undefined
01:53:24 
01:53:24 Error stack trace:
01:53:24 TypeError: Cannot read property 'length' of undefined
01:53:24     at /app/e/node_modules/testarmada-magellan/bin/magellan:321:26
01:53:24     at _fulfilled (/app/e/node_modules/q/q.js:834:54)
01:53:24     at self.promiseDispatch.done (/app/e/node_modules/q/q.js:863:30)
01:53:24     at Promise.promise.promiseDispatch (/app/e/node_modules/q/q.js:796:13)
01:53:24     at /app/e/node_modules/q/q.js:604:44
01:53:24     at runSingle (/app/e/node_modules/q/q.js:137:13)
01:53:24 …
```
=> Fix unhelpful stack trace error when choosing a browser profile that no longer exists

src/test_runner.js
This PR adds a magellan-injected timestamp into the beginning of every `stdout` string we collect from child processes.
This helps users debug whether their test framework process is taking a very long time to effectively start and begin to consume its `individual test timeout budget`.
For example, **if a test takes 3 minutes to start emitting output to `stdout`**, the feature introduced by this PR will illuminate that problem, because at the beginning of the output we will see the `Magellan child process start` with a timestamp, showing a 3 minute gap between starting the process and getting further output.
/cc @geekdave @archlichking @chaseadamsio @ThaiWood
=> Mark process time start in stdout of child processes

src/util/load_relative_module.js, test/utils/load_relative_module.js
This makes it easier to debug why magellan won't start. For instance, you'll see
`Error: Error: Module version mismatch. Expected 48, got 46.`
instead of 
`TypeError: Cannot read property 'initialize' of null`
if the node version's don't match.
=> Throw the error if unable to require module

package.json, src/test_runner.js, test/test_runner.js
allow executor to attach additional logs to magellan worker. this is helpful when the additional logs are needed from executor by user, like the replay of test run on vendor's env.
=> Attach logs

src/profiles.js, test/profiles.js
There was an issue in existing logic where duplicate profiles would be selected for the test run if the `--profile` option was used.
For example,
`--profile= http://github.com/browser_profiles.json#browser1,browser2` where we had a `browser1` and `browser2` consisted of:
```
"browser1": [
{ "browser": "microsoftedge_14_Windows_10_Desktop", "resolution": "1280x1024" },
{ "browser": "safari_10_OS_X_10_11_Desktop", "resolution": "1280x960" },
{ "browser": "chrome_latest_Windows_10_Desktop", "resolution": "1280x1024" },
{ "browser": "IE_11_Windows_10_Desktop", "resolution": "1280x1024" },
{ "browser": "firefox_46_Windows_2012_R2_Desktop", "resolution": "1280x1024" }
],
"browser2": [
{ "browser": "safari_9_OS_X_10_11_Desktop", "resolution": "1280x960" },
{ "browser": …
```
=> [PATCH] Remove duplicate profiles from the test run

package.json, src/bail.js, src/cli.js, src/cli_help.js, src/help.js, src/settings.js, src/strategies/bail_early.js, src/strategies/bail_fast.js, src/strategies/bail_never.js, src/test_runner.js, test/bail.js, test/cli_help.js, test/test_runner.js
This PR allows magellan to use customized bail strategy. The previous bail rules (bail fast, bail early, bail timely and bail never) are still supported, but their command line arguments are marked as deprecated and will be removed from magellan in next release. Bail rules are transformed into bail strategy files under `./src/strategies/` and will be put into separate repo as magellan bail strategies.
This PR contains following changes
1. allows to create customized bail strategy for magellan
2. deprecates previous bail arguments
3. moves all bail logic to separate files, and be ready for swipe them out in next release.
=> Add support for bail strategy

package.json, src/cli.js
this PR enhances the argument handling issue where `--magellan_arg_1=false` will be passed to `magellan_arg_1:'false'` from margs.
=> fix strategy issue

src/util/port_util.js, test/utils/port_util.test.js
Changed logic to check all the ports in between current port and next port, calculated by BASE_PORT_SPACING.
So if BASE_PORT_START is 12000 and BASE_PORT_SPACING is 3, it will check ports 12000, 12001, and 12002. If any of those ports are not available, it will check 12003 through 12005, and so on.
=> Updated logic to check every port in the range, and move to the next set

doc/FRAMEWORK_PLUGINS.md
There were a few things in the plugin doc that don't seem current.
`iterator` requires tests to also implement a `filename` property that `magellan` uses to print found tests. This could also be moved to use `toString` but I figured a doc update was simpler for now.
https://github.com/TestArmada/magellan/blob/189dd6001e8eb2696caf69e6d987b3104cbd8d33/src/cli.js#L335
`filters` receive an array of tests (from `iterator`) as the first parameter and the filter as the second parameter (see [magellan-nightwatch-plugin](https://github.com/TestArmada/magellan-nightwatch-plugin/blob/22428883264cc42042ebad163b508599ce3f619c/lib/group_filter.js#L10)) and must return a list of tests to run.
=> Update plugin docs to existing api

bin/magellan
The following anywhere in the process will cause magellan to abort and exit:
require('fs').createReadStream( '/tmp/' );
This prevents that.
=> Do not abort on uncaught exception

package-lock.json, package.json, src/util/childProcess.js, test/utils/child_process.test.js
Quite simple, use pipes in the ChildProcess. 
This fixes a bug in where the reporters can be given the "unfiltered" nightwatch debug log, which is way to large for any reporter to deal with.
Cheers!
below is a screen of the bug this PR fixes
=> Use strictly pipes in ChildProcess, also this fixes a bug with the reporters getting unfiltered stdout

package.json, src/util/childProcess.js, test/utils/child_process.test.js
users are having issue with the logging being too verbose.
this has been fix by making the whitelist be more "specific" ... "error" and "warn" strings are too generic.
the new white list should filter only what we need
=> made-whitelist-more-specific

package.json, src/util/childProcess.js
This PR reduces the stdout logging verbosity.
It accomplishes this goal in two ways
1) ignore the error chunks related to `/timeouts/async_script`
2) improve the line-by-line filtering indicators to also include `✖`
also some nice code clean-up :)
=> Make the stdout logging less verbose
